default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: healer_development

test:
  <<: *default
  database: healer_test

production:
  <<: *default
  database: healer_production
  username: healer
  password: <%= ENV["HEALER_DATABASE_PASSWORD"] %>
